pool:
  vmImage: 'ubuntu-latest'

variables:
  project: campo

stages:
  - stage: Build
    jobs:
    - job: Build
      steps:
      - script: |
          dotnet restore
          dotnet build
          dotnet publish -o $(Pipeline.Workspace)
        workingDirectory: "src"
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)' 
          artifactName: 'farmer'
  - stage: Dev
    jobs:
    - deployment: DevDeploy
      environment: '$(project)-dev'
      strategy:
        runOnce:
          deploy:
            steps:
            - script: echo "hello, $(project)-dev"
  - stage: Staging
    jobs:
    - deployment: StagingDeploy
      environment: '$(project)-staging'
      strategy:
        runOnce:
          deploy:
            steps:
            - script: echo "hello, $(project)-staging"